name: 32-bit test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        size: ['64b', '32b']
        golang: ['1.21.10', '1.22.3']
        exclude:
          - os: windows-latest
            size: '32b'

    runs-on: ${{matrix.os}}

    steps:
    - name: Matrix is ${{matrix.os}} / ${{matrix.size}} - Go is ${{matrix.golang}}
      run: date

    - name: Setup Alpine Linux ${{matrix.size}}
      uses: jirutka/setup-alpine@v1
      if: ${{ matrix.size == '32b' }}
      with:
        arch: x86
        packages: >
          make 
          git 
          gcc 
          musl-dev
          wget
          tar

    - name: getconf x86
      if: ${{ matrix.size == '32b' }}
      run: |
        wget -nv https://go.dev/dl/go${{matrix.golang}}.linux-386.tar.gz
        tar xf go*
        export PATH=$PATH:$(pwd)/go/bin
        go version
        getconf LONG_BIT
      shell: alpine.sh {0}

    - name: getconf x64
      run: getconf LONG_BIT

